<?php

namespace Container9b3IKdM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FlashcardsController' shared autowired service.
     *
     * @return \App\Controller\FlashcardsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FlashcardsController.php';

        $container->services['App\\Controller\\FlashcardsController'] = $instance = new \App\Controller\FlashcardsController(($container->privates['App\\Repository\\FlashcardsRepository'] ?? $container->load('getFlashcardsRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\FlashcardsController', $container));

        return $instance;
    }
}
