<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCaR1AxM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCaR1AxM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCaR1AxM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCaR1AxM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCaR1AxM\App_KernelDevDebugContainer([
    'container.build_hash' => 'CaR1AxM',
    'container.build_id' => 'd1c19fa3',
    'container.build_time' => 1725461541,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCaR1AxM');
