<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRg53UqG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRg53UqG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRg53UqG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRg53UqG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRg53UqG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rg53UqG',
    'container.build_id' => '07668d0c',
    'container.build_time' => 1724784928,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRg53UqG');
