<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.8ab7f0c8.js',
                '/build/860.3d9cb7af.js',
                '/build/app.d4c3246f.js',
            ],
            'css' => [
                '/build/app.d9309bd8.css',
            ],
        ],
    ],
],

]];
